### ISSUE TITLE
How can I configure ACH method.

### ISSUE THREAD

**Issue by skabirgithub** [adyen-examples/adyen-php-online-payments#8] opened 2021-08-12 12:26 UTC
Ach always says Invalid Account no. please tell me where to change ach credentials

**Comment by jlengrand** [comment] 2022-02-02 14:06
Sorry @skabirgithub , given the issue is 6 months old I'll close it. If you still have issues please open a new issue or reopen this one

**Closed** 2022-02-02 14:06 UTC
