### ISSUE TITLE
Error occurred. Look at console for details

### ISSUE THREAD

**Issue by ckinfotech** [adyen-examples/adyen-php-online-payments#2] opened 2021-02-17 06:04 UTC
Error occurred. Look at console for details i m facing  this issue when i run this demo.

**Comment by ckinfotech** [comment] 2021-02-17 06:29
SyntaxError: Unexpected token < in JSON at position 0

**Comment by deepu105** [comment] 2021-02-18 09:42
Hi @ckinfotech sorry as I'm unable to reproduce this, can you let me know what exactly you did? like what payment method did you try and when did the error occur?

**Comment by anesuc** [comment] 2021-05-08 14:53
I am having the same error. Mine doesn't even print anything in the console. I'm using test Mastercard number (tried 2 others) from https://docs.adyen.com/development-resources/test-cards/test-card-numbers#mastercard:
5555 3412 4444 1115
Name: Any name (it doesn't give any name for Mastercard smaples)
Expiry date: 03/30
CVC: 737

**Comment by michaelpaul** [comment] 2021-08-18 17:28
Hi @deepu105, I can reproduce this error. It occurred because my API key had a # symbol. The "dotenv" parser ignores anything after the # symbol assuming it's an inline comment.

The simplest possible solution it's to add quotes around my token. 

Here it's an example test to reproduce the issue. Given a `.env.testing` with:

```
API_KEY=all-good#ignored-as-comment
API_KEY_QUOTED="all-good#not-a-comment"
```

This test will pass: 

```php
<?php

namespace Tests\Feature;

use Tests\TestCase;

class ExampleTest extends TestCase
{
    public function testApiKeyWithHashtag()
    {
        $this->assertEquals(env('API_KEY'), 'all-good');
        $this->assertEquals(env('API_KEY_QUOTED'), 'all-good#not-a-comment');
    }
}
```

**Comment by jlengrand** [comment] 2022-02-02 14:07
Hey @michaelpaul and @anesuc , is the error still present for you?

**Comment by michaelpaul** [comment] 2022-02-17 19:58
Hi @jlengrand, I don't get the error when I quote my keys. Maybe this can be added to the `.env.example`:

```
API_KEY="fill your key inside these quotes"
```

**Comment by jlengrand** [comment] 2022-02-20 22:12
Hum, I've just tried without being able to reproduce the issue. The error can happen in case the URL is not part of the list of allowed origin though.

I'm gonna close this and update the README, but I'm happy to reopen this in case you are still running into issues.

**Closed by jlengrand** 2022-02-20 22:12 UTC
